name: Nuget package release

on:
  create:
    tags:
    - '*.*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - name: Pack Nuget package
      run: dotnet pack --configuration Release -p:PackageVersion=$RELEASE_VERSION
    - name: Push Nuget package
      run: dotnet nuget push **/*.nupkg
            --api-key ${{ secrets.NUGET_API_KEY }}
            --source https://api.nuget.org/v3/index.json